Sprint 1
AlSudar/middle.messenger.praktikum.yandex pull request #1
Opened 2021-10-17 22:31 UTC by AlSudar

2021-10-18 13:40 UTC, bhoodream requested changes
Хорошая работа! Но нужно внести некоторые правки. Нужно поработать над комментами по коду + перечисленные ниже нюансы:

- [x] `package-lock.json` не нужно игнорировать, это важный файл, который гарантирует адекватную сборку проекта. Если интересно, погугли более развернутый ответ, почему `package-lock.json` важен
- [ ] заметил, что у тебя в `README.md` вообще не используется никакое форматирование. Синтаксис `.md` файлов поддерживает минимально необходимую верстку, вот тут можно посмотреть https://www.markdownguide.org/basic-syntax/
- [ ] не нашел ссылки на следующие ресурсы:
    - [ ] развернутый стенд в netlify
    - [ ] макеты в figma 
- [ ] .cache нужно добавить в `.gitignore`, а то уж слишком много правок после сборки :)
- [ ] если сбилдить проект через `npm run build` и запустить его как `node ./index.js`, то он на 3000 порту просто раздает файлы репозитори. Нужно чтобы сервер запущенный с помощью `node ./index.js` раздавал сбилженный `./dist`.

2021-10-18 13:40 UTC, bhoodream commented on src/components/buttonPrimary/index.pug
> +button.c-button.c-button_primary= buttonPrimaryText
Кнопкам нужен `type`, посмотри почему :) https://stackoverflow.com/questions/41904199/whats-the-point-of-button-type-button

2021-10-18 13:40 UTC, bhoodream commented on src/layout/index.pug
> +    link(rel="stylesheet", href='../../assets/main.scss')
Вот здесь ты подключил все стили проекта, и каждая страница будет содержать их, хотя они определенно не нужны все на каждой странице...

2021-10-18 13:40 UTC, bhoodream commented on src/pages/login/index.pug
> +      p.form__password Нет аккаунта?
Это по идее ссылка на странице регистрации

2021-10-18 13:40 UTC, bhoodream commented on src/pages/register/index.pug
> +      p.form__login Войти
А это ссылка на страницу авторизации

2021-10-18 13:40 UTC, bhoodream commented on static/styles/index.css
> +@import "/src/assets/main.scss";
Этот файл нужно удалить, так как они не является исходником

2021-10-18 13:40 UTC, bhoodream commented on src/pages/userProfile/index.js
> +const popup = document.querySelector(".p-user-profile__popup");
Конечно хорошо что ты сейчас попробовал реализовать функционал попапов, но в будущем такой код лучше не пиши, потому что он плохо сопровождается и вообще никак не масштабируется.

Декларативная, компонентная разработка будет хорошо раскрыта в будущих спринтах, а пока от тебя требуется просто качественная статика :)

2021-10-18 19:29 UTC, AlSudar commented on src/assets/pages/_index.scss
> +@import "../../pages/login/index";
Мне кажется что описанным тобой способом (если я правильно его понял) будет сложнее масштабировать проект и внедрять новые компоненты в существующий код

2021-10-18 21:52 UTC, bhoodream commented on src/assets/pages/_index.scss
> +@import "../../pages/login/index";
Странно, что тебе так кажется...

2021-10-18 21:57 UTC, bhoodream approved these changes
Хорошая работа над ошибками! От меня АПРУВ, правда нужно еще пару правок сделать, чтобы жилось лучше:

- [ ] удалить папку `.cache`, ~800 правок в ПРе это не ок
- [ ] `.md` имеет свой синтаксис, который позволяет выделять: заголовки, списки, ссылки, код и тд и тп. Ты добавил не нужные `<i/b>` обертки, да еще и в `html`. Это совсем не то, что я имел ввиду
- [ ] ссылка на нетлифай не та, должна быть что-то типа https://sleepy-ptolemy-7f8b8b.netlify.app/

2021-10-20 02:31 UTC, bhoodream commented on src/assets/pages/_index.scss
> +@import "../../pages/login/index";
В компонентном подходе каждый модуль самодостаточная единица, то что ты говоришь как раз делаешь ты, а я предлагаю, чтобы подключаемый компонент сам подключал все что ему нужно. В общем, поизучай эту тему, если интересно.

2021-11-30 08:04 UTC, merged